# -*- encoding: utf-8 -*-

=begin
#Lethean Binary API

#Functionality to simplify using LTHN

The version of the OpenAPI document: 1.2.2
Contact: contact@lethean.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "letheanSDP/version"

Gem::Specification.new do |s|
  s.name        = "letheanSDP"
  s.version     = letheanSDPClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["contact@lethean.io"]
  s.homepage    = "https://lt.hn"
  s.summary     = "Lethean Binary API Ruby Gem"
  s.description = "Functionality to simplify using LTHN"
  s.license     = "EUPL-1.2"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
