=begin
#Lethean Binary API

#Functionality to simplify using LTHN

The version of the OpenAPI document: 1.2.2
Contact: contact@lethean.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for letheanSDPClient::VpnApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VpnApi' do
  before do
    # run before each test
    @api_instance = letheanSDPClient::VpnApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VpnApi' do
    it 'should create an instance of VpnApi' do
      expect(@api_instance).to be_instance_of(letheanSDPClient::VpnApi)
    end
  end

  # unit tests for start_letheand
  # @param data_dir Returns the binary version
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :version Returns the binary version
  # @return [nil]
  describe 'start_letheand test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
