=begin
#Lethean Binary API

#Functionality to simplify using LTHN

The version of the OpenAPI document: 1.2.2
Contact: contact@lethean.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

module letheanSDPClient
  VERSION = '1.0.0'
end
